---
name: service-backup

director_uuid: e92258ed-c38a-4ea1-b7d4-fbef77d8e5d0

releases:
- name: service-backup
  version: latest

properties:
  service-backup:
    blobstore:
      bucket_name: service-backup-test
      bucket_path: /foo
      access_key_id: 
      secret_access_key: 
    source_folder: /var/vcap/store/
    source_executable: ls
    cron_schedule: '* * * * *'

jobs:
- name: service-backup
  instances: 1
  resource_pool: service-backup
  persistent_disk: 1024
  networks:
  - name: service-backup
    static_ips:
    - 10.0.36.6
  templates:
  - {release: service-backup, name: service-backup}


networks:
  - name: service-backup
    type: manual
    subnets:
      - range: 10.0.36.0/24
        reserved:
          - 10.0.36.2 - 10.0.36.5
          - 10.0.36.254
        static:
          - 10.0.36.6 - 10.0.36.8
        dns: [10.0.0.2]
        gateway: 10.0.36.1
        cloud_properties:
          subnet: subnet-ac9ad8f5

resource_pools:
- name: service-backup
  network: service-backup
  cloud_properties:
    instance_type: m3.large
    availability_zone: eu-west-1a
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

compilation:
  workers: 1
  network: service-backup
  cloud_properties:
    instance_type: c4.large
    availability_zone: eu-west-1a
    ephemeral_disk:
      size: 30000
      type: gp2


update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
