---
aws-cli/awscli-bundle.zip:
  object_id: ea815e4b-235a-4494-a53b-0336b29a2de5
  sha: db33b4740a670c9fb3bc5515cd7f9861fa1b1b13
  size: 5207424
python/Python-2.7.8.tgz:
  object_id: 5fe0b8e4-9b77-4499-8f5d-d76b93254b1d
  sha: 511960dd78451a06c9df76509635aeec05b2051a
  size: 14846119
golang/go1.4.2.linux-amd64.tar.gz:
  object_id: 4849b2df-9250-4727-afc6-90533b84e195
  sha: 5020af94b52b65cc9b6f11d50a67e4bae07b0aff
  size: 62442704
