libffi/libffi-3.4.6.tar.gz:
  size: 1391684
  object_id: dbefd80e-f3ee-4437-4ace-6ded85e045e9
  sha: sha256:b0dea9df23c863a7a50e825440f3ebffabd65df1497108e5d437747843895a4e
python/Python-3.12.7.tgz:
  size: 27016272
  object_id: 03564e2a-28aa-41f5-7496-c517c061e67f
  sha: sha256:73ac8fe780227bf371add8373c3079f42a0dc62deff8d612cd15a618082ab623
sqlite/sqlite-autoconf-3470100.tar.gz:
  size: 3328564
  object_id: e6fa1194-01e8-406b-694e-08eff15b43b7
  sha: sha256:416a6f45bf2cacd494b208fdee1beda509abda951d5f47bc4f2792126f01b452
