go/go1.21.3.linux-amd64.tar.gz:
  size: 66641773
  object_id: 560bf6f1-70b3-446a-7dff-d13767852da6
  sha: sha256:1241381b2843fae5a9707eec1f8fb2ef94d827990582c7c7c32f5bdfbfd420c8
libffi/libffi-3.4.4.tar.gz:
  size: 1362394
  object_id: 893443d4-01f7-41d1-6990-178fecd10a3a
  sha: sha256:d66c56ad259a82cf2a9dfc408b32bf5da52371500b84745f7fb8b645712df676
python/Python-3.12.0.tgz:
  size: 27195214
  object_id: ec7010fb-117b-4c29-4e26-cce70700b727
  sha: sha256:51412956d24a1ef7c97f1cb5f70e185c13e3de1f50d131c0aac6338080687afb
python/pip-23.3.tar.gz:
  size: 2131482
  object_id: ef5ef10e-042e-4f34-7128-495793ada08d
  sha: sha256:bb7d4f69f488432e4e96394612f43ab43dd478d073ef7422604a570f7157561e
sqlite/sqlite-autoconf-3420000.tar.gz:
  size: 3148813
  object_id: 5de2557d-1b88-45b3-633e-872fa8070ac9
  sha: sha256:7abcfd161c6e2742ca5c6c0895d1f853c940f203304a0b49da4e1eca5d088ca6