libffi/libffi-3.4.6.tar.gz:
  size: 1391684
  object_id: 3e8cf1da-9c68-4f5a-61a0-1a8c07a93b1c
  sha: sha256:b0dea9df23c863a7a50e825440f3ebffabd65df1497108e5d437747843895a4e
python/Python-3.12.6.tgz:
  size: 27009716
  object_id: 15e25316-681f-4155-7b0a-1a2344b91d57
  sha: sha256:85a4c1be906d20e5c5a69f2466b00da769c221d6a684acfd3a514dbf5bf10a66
sqlite/sqlite-autoconf-3460100.tar.gz:
  size: 3265571
  object_id: bbbc40df-0fc0-4cc3-704b-ec32239e93e3
  sha: sha256:67d3fe6d268e6eaddcae3727fce58fcc8e9c53869bdd07a0c61e38ddf2965071
