---
aws-cli/awscli-bundle.zip:
  object_id: 1ddaf076-758d-4a77-b4af-7c8378d5a2a9
  sha: 60a57058fa208072ee056f3b746f7d57bb58699f
  size: 6596271
python/Python-2.7.11.tgz:
  object_id: ef4401b7-48f4-4312-8e5a-86c001cc3cf0
  sha: 62a0b1b703d42999cc4aa9ee3c55eb7efe35802a
  size: 16856409
golang/go1.6.linux-amd64.tar.gz:
  object_id: c42f2044-02d3-4dac-93ca-0351528a60fd
  sha: 01a6a28dbe31a53103b600979bbbbd63a8104456
  size: 84799480
blobxfer/azure-common-1.1.1.zip:
  object_id: 52715fb1-f94f-4b46-8481-0f489f457d0b
  sha: f5ca189aaa62b56a9fcdeadea5d5ebe16aec6588
  size: 6543
blobxfer/azure-storage-0.30.0.zip:
  object_id: 79ba86d5-1301-46f8-ac14-9307739185fc
  sha: 62de894f490869a364910c3c3dfa93930e5814ba
  size: 153988
blobxfer/blobxfer-0.10.0.tar.gz:
  object_id: 2172f77f-d099-4cf5-923b-dd8fbf5703ef
  sha: 7dfd2d28c3122ca520e553ab223ee87aea3d6342
  size: 43929
blobxfer/python-dateutil-2.4.2.tar.gz:
  object_id: 6b1adbbe-bcd2-4cf5-983c-ab9ce85324dd
  sha: 1d975f5db65306a61f4353ef00308ec806f47f54
  size: 209120
blobxfer/requests-2.9.1.tar.gz:
  object_id: 72e521bd-6184-45cf-93b8-d1bb2e665637
  sha: 172838c7115c0c1f9cb8663b025f4599915bb805
  size: 695285
blobxfer/setuptools-20.6.7.tar.gz:
  object_id: f2d4bdd4-1e19-4deb-b456-e29634fed5d6
  sha: 8afa042dece06be473b025e628d3585ab5d27de3
  size: 675428
