aws-cli/awscli-bundle-2.13.3.zip:
  size: 58117850
  object_id: bc96aa96-9a4b-483b-58a4-1756112c93ee
  sha: sha256:25a81479d3a00c7875a98a7fe341d4c924d030f04c042fa6deebe3e499fa0d1d
blobxfer/asn1crypto-0.22.0.tar.gz:
  size: 84508
  object_id: 27cbba76-d420-4906-43f7-1a4665263171
  sha: c4f60b52dd06e3fd0ed568a741e968aaccd2e3e5
blobxfer/azure-common-1.1.8.zip:
  size: 16849
  object_id: 22e4842e-6b21-4f28-5e2f-700d00cefe9a
  sha: 0b8025e5acba3a79bfd494f4dd7d079abfe09cc9
blobxfer/azure-storage-blob-0.37.1.tar.gz:
  size: 69898
  object_id: a1ccae34-8306-4488-7e90-94478fd3a0b4
  sha: 8ab0d8787d33c299dd3a72074a959b2aebe742e4
blobxfer/azure-storage-common-0.37.1.tar.gz:
  size: 40939
  object_id: 8e32e789-a85e-4554-6b6d-87129226e478
  sha: 8970c249a1b1bbc6071807343fafaea79db831e0
blobxfer/azure-storage-file-0.37.0.tar.gz:
  size: 34040
  object_id: 990b9639-7fed-41f5-772e-63c95d22c5c3
  sha: 2cca46349add9998de53ddc9e4fa62852fd57a49
blobxfer/bitstring-3.1.5.zip:
  size: 624428
  object_id: b735893e-caca-4274-4cda-afe628195a8f
  sha: 96ffe09e9788a22a3d75ad4a629d24bfc70bdac3
blobxfer/blobxfer-1.11.0.tar.gz:
  size: 166060
  object_id: 56c22507-29f1-4df4-7865-49fbf77a06b5
  sha: sha256:b80429b46bd1e1a0f36493d49d1cef9653465b8190adc709fde4e545fe6d1cd0
blobxfer/certifi-2017.11.5.tar.gz:
  size: 329246
  object_id: 7fb6ac51-be9e-4889-4a2f-68d91b12d6a5
  sha: 8e4574685163771ee40604d7dd89fe60b9461790
blobxfer/cffi-1.11.2.tar.gz:
  size: 435142
  object_id: ed6a78e5-a29c-4a4f-7ae5-711588e28021
  sha: 04d2df85eb1921630b4f9206886737eb37200c19
blobxfer/chardet-3.0.4.tar.gz:
  size: 1868453
  object_id: 8b4965bb-e3fd-41f6-6772-f8f4a6237fdb
  sha: 4766fb07e700945a7085d073257f1f320d037ce8
blobxfer/click-6.7.tar.gz:
  size: 279019
  object_id: 0282e131-efe6-43e2-55ee-ccdb97849105
  sha: c16e7cb561a40c385ae8d1a50528e549cc1d8e94
blobxfer/cryptography-2.1.4.tar.gz:
  size: 441557
  object_id: 42d114f8-d8e0-4c62-67eb-0decf87b4a21
  sha: 0c4d8104c78e6e3e94ca8bdb1d99a365f29673e7
blobxfer/future-0.16.0.tar.gz:
  size: 824484
  object_id: 1027f24b-41ff-4641-6b90-e8d83a0c23a9
  sha: 86ed881acef874d04576b9df03c29d25ad2cd25f
blobxfer/idna-2.6.tar.gz:
  size: 135992
  object_id: c9d13c29-e0c8-490a-5f49-ffbdd6c3803c
  sha: abf5e2e7d8f52dd00e658f1ead4eb9f4d2240bf4
blobxfer/ipaddress-1.0.19.tar.gz:
  size: 32854
  object_id: ff06f39f-d753-4124-69cd-1cfa477c90f7
  sha: 9a6184cb3da3d967adc3dde4606614f0dd00ab47
blobxfer/libffi-3.2.1.tar.gz:
  size: 940837
  object_id: 5aa1d6b7-d5e2-40e1-72a4-cd98638714ca
  sha: 280c265b789e041c02e5c97815793dfc283fb1e6
blobxfer/pycparser-2.18.tar.gz:
  size: 245897
  object_id: 2d837d9b-dfdc-4542-67c8-041f7954ca32
  sha: 1c75af69ae6273b1f1f531744f87d060965ed85d
blobxfer/python-dateutil-2.6.1.tar.gz:
  size: 241428
  object_id: 2926fe62-6243-4880-4203-ccac771b341c
  sha: db2ace298dee7e47fd720ed03eb790885347bf4e
blobxfer/requests-2.18.4.tar.gz:
  size: 126224
  object_id: 10e724ea-5b95-45ff-4f12-a9f2ecebb3d1
  sha: f5e1dbba5a12ff2df063333fd2bf071e24659b63
blobxfer/ruamel.ordereddict-0.4.13.tar.gzz:
  size: 57711
  object_id: a601e191-5fb4-49d9-5495-fb8468865ac9
  sha: d1f3187f0df90522e5bcd5235be3aa75390cc663
blobxfer/ruamel.yaml-0.15.34.tar.gz:
  size: 260561
  object_id: 8bd35a20-40ad-4e8e-65bb-2776130d74e7
  sha: 2108aa705128d088bb739f794cd3c5f7497a8b19
blobxfer/six-1.11.0.tar.gz:
  size: 29860
  object_id: 7737f486-2987-4fde-7777-9f8296eb44d3
  sha: 3647372a0e104e7b53bd477762392024e1083ac0
blobxfer/urllib3-1.22.tar.gz:
  size: 226083
  object_id: 3be8363d-60d9-4c0f-4912-5d82c238b12f
  sha: 02c623c3bdceda4ef5bffdafdda472d2d9e34ef1
go/go1.10.linux-amd64.tar.gz:
  size: 119905205
  object_id: a736e772-073c-4ab0-7d2f-60ac540a91ce
  sha: 693e2dfd99ef2d608b41c450efd9d277bf2a7f2f
pkg-config/pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 0e026ffc-8f7a-4e51-4b8e-1e30099469d0
  sha: 76e501663b29cb7580245720edfb6106164fad2b
python/Python-3.11.4.tgz:
  size: 26526163
  object_id: c4ce5430-af2a-40c9-7200-c883dd27b4fd
  sha: sha256:85c37a265e5c9dd9f75b35f954e31fbfc10383162417285e30ad25cc073a0d63
python/pip-21.2.3.tar.gz:
  size: 1572274
  object_id: be28e377-dda6-4213-5256-89eb90104992
  sha: sha256:91e66f2a2702e7d2dcc092ed8c5ebe923e69b9997ea28ba25823943bcd3bf820
