libffi/libffi-3.5.1.tar.gz:
  size: 1419757
  object_id: b04ad285-a6fa-402c-5989-1636e036cab2
  sha: sha256:f99eb68a67c7d54866b7706af245e87ba060d419a062474b456d3bc8d4abdbd1
python/Python-3.12.11.tgz:
  size: 27126512
  object_id: e1fd6108-901f-465e-6883-f9a0ddc8fb05
  sha: sha256:7b8d59af8216044d2313de8120bfc2cc00a9bd2e542f15795e1d616c51faf3d6
sqlite/sqlite-autoconf-3500200.tar.gz:
  size: 3172568
  object_id: 9676673f-1f71-4200-4090-e34d560be6da
  sha: sha256:84a616ffd31738e4590b65babb3a9e1ef9370f3638e36db220ee0e73f8ad2156
