---
aws-cli/awscli-bundle.zip:
  object_id: 1ddaf076-758d-4a77-b4af-7c8378d5a2a9
  sha: 60a57058fa208072ee056f3b746f7d57bb58699f
  size: 6596271
python/Python-2.7.11.tgz:
  object_id: ef4401b7-48f4-4312-8e5a-86c001cc3cf0
  sha: 62a0b1b703d42999cc4aa9ee3c55eb7efe35802a
  size: 16856409
blobxfer/azure-common-1.1.4.zip:
  object_id: 55696515-f72a-4ecf-afda-2d6d95f5421d
  sha: 9780efee38fbaaeaeb697232eb22f18638a2d99f
  size: 6575
blobxfer/azure-storage-0.32.0.zip:
  object_id: 5da9859e-353b-4f4d-9aa9-e8e7bdf7763e
  sha: 17aae39fd581e3ed4795c2654568d7c7b480e179
  size: 164004
blobxfer/blobxfer-0.11.1.tar.gz:
  object_id: 347bda4b-8f3c-4b71-8111-9ce00f314fbc
  sha: c7dfb991683e0099dd9769487f378203fd08d849
  size: 50482
blobxfer/python-dateutil-2.4.2.tar.gz:
  object_id: 6b1adbbe-bcd2-4cf5-983c-ab9ce85324dd
  sha: 1d975f5db65306a61f4353ef00308ec806f47f54
  size: 209120
blobxfer/requests-2.10.0.tar.gz:
  object_id: 11700f1d-bcd1-4841-bb3e-78315f05657c
  sha: 1b9a2395402692262fc61fa15bedbc3e112b1029
  size: 477617
blobxfer/setuptools-20.6.7.tar.gz:
  object_id: f2d4bdd4-1e19-4deb-b456-e29634fed5d6
  sha: 8afa042dece06be473b025e628d3585ab5d27de3
  size: 675428
golang/go1.6.2.linux-amd64.tar.gz:
  object_id: 2cc9ee78-d3a2-4415-8302-db88c2c981da
  sha: b8318b09de06076d5397e6ec18ebef3b45cd315d
  size: 84840658
blobxfer/six-1.10.0.tar.gz:
  object_id: 9bdfbf5d-32c8-47d1-9047-c2ef5c9b259f
  sha: 30d480d2e352e8e4c2aae042cf1bf33368ff0920
  size: 29630
