libffi/libffi-3.5.1.tar.gz:
  size: 597581
  object_id: 03308cee-c31a-4073-6ca0-10f45430b0da
  sha: sha256:ca180dccd8e26900a169efd6e09207eaa0a9be268010b8faec10476c9c4951d9
python/Python-3.12.11.tgz:
  size: 27126512
  object_id: e1fd6108-901f-465e-6883-f9a0ddc8fb05
  sha: sha256:7b8d59af8216044d2313de8120bfc2cc00a9bd2e542f15795e1d616c51faf3d6
sqlite/sqlite-autoconf-3500200.tar.gz:
  size: 3172568
  object_id: 9676673f-1f71-4200-4090-e34d560be6da
  sha: sha256:84a616ffd31738e4590b65babb3a9e1ef9370f3638e36db220ee0e73f8ad2156
