---
python/Python-2.7.11.tgz:
  object_id: ef4401b7-48f4-4312-8e5a-86c001cc3cf0
  sha: 62a0b1b703d42999cc4aa9ee3c55eb7efe35802a
  size: 16856409
blobxfer/python-dateutil-2.4.2.tar.gz:
  object_id: 6b1adbbe-bcd2-4cf5-983c-ab9ce85324dd
  sha: 1d975f5db65306a61f4353ef00308ec806f47f54
  size: 209120
blobxfer/setuptools-20.6.7.tar.gz:
  object_id: f2d4bdd4-1e19-4deb-b456-e29634fed5d6
  sha: 8afa042dece06be473b025e628d3585ab5d27de3
  size: 675428
blobxfer/azure-common-1.1.4.zip:
  object_id: dfe5780a-a249-4c8f-b5d5-6f55c9c39292
  sha: 9780efee38fbaaeaeb697232eb22f18638a2d99f
  size: 6575
blobxfer/azure-storage-0.32.0.zip:
  object_id: 3071aefa-ba11-47b2-b064-aecd1bd592a5
  sha: 17aae39fd581e3ed4795c2654568d7c7b480e179
  size: 164004
blobxfer/blobxfer-0.11.1.tar.gz:
  object_id: cd20e00c-318e-4241-ac19-b0b2526d889f
  sha: c7dfb991683e0099dd9769487f378203fd08d849
  size: 50482
blobxfer/requests-2.10.0.tar.gz:
  object_id: 0564ec27-2e36-4405-bd6b-b8d6499b40bd
  sha: 1b9a2395402692262fc61fa15bedbc3e112b1029
  size: 477617
blobxfer/six-1.10.0.tar.gz:
  object_id: 9bdfbf5d-32c8-47d1-9047-c2ef5c9b259f
  sha: 30d480d2e352e8e4c2aae042cf1bf33368ff0920
  size: 29630
aws-cli/awscli-bundle.zip:
  object_id: e2cb3da2-2c5e-4f8d-b62c-830b3ab4d777
  sha: 9c7652a1ed539732eb8fa43df91cb7f928d6b9d0
  size: 7058663
golang/go1.7.3.linux-amd64.tar.gz:
  object_id: c55ab2ea-416f-4a3d-9d23-06fed48348f1
  sha: ead40e884ad4d6512bcf7b3c7420dd7fa4a96140
  size: 82565628
