libffi/libffi-3.4.6.tar.gz:
  size: 1391684
  object_id: dbefd80e-f3ee-4437-4ace-6ded85e045e9
  sha: sha256:b0dea9df23c863a7a50e825440f3ebffabd65df1497108e5d437747843895a4e
python/Python-3.12.6.tgz:
  size: 27009716
  object_id: ffed2f27-73f4-4e10-43f6-ac6fb7ef8f13
  sha: sha256:85a4c1be906d20e5c5a69f2466b00da769c221d6a684acfd3a514dbf5bf10a66
sqlite/sqlite-autoconf-3460100.tar.gz:
  size: 3265571
  object_id: 4ddd0da6-58f4-40d9-5900-a52aeb5e3f6b
  sha: sha256:67d3fe6d268e6eaddcae3727fce58fcc8e9c53869bdd07a0c61e38ddf2965071
