aws-cli/awscli-bundle-2.13.3.zip:
  size: 58117850
  object_id: 331ed99a-9eea-4b8f-589d-f7f6704ce5c7
  sha: sha256:25a81479d3a00c7875a98a7fe341d4c924d030f04c042fa6deebe3e499fa0d1d
go/go1.10.linux-amd64.tar.gz:
  size: 119905205
  object_id: a736e772-073c-4ab0-7d2f-60ac540a91ce
  sha: 693e2dfd99ef2d608b41c450efd9d277bf2a7f2f
python/Python-3.11.4.tgz:
  size: 26526163
  object_id: f02a6bb1-0cbc-46cb-46d3-32b64c366655
  sha: sha256:85c37a265e5c9dd9f75b35f954e31fbfc10383162417285e30ad25cc073a0d63
python/pip-9.0.1.tar.gz:
  size: 6109437
  object_id: 8f39a555-5b4f-4664-6659-21cea98e304e
  sha: 39b5840f6a9e6888d56a78beb447a064aeaf1592
