go/go1.21.3.linux-amd64.tar.gz:
  size: 66641773
  object_id: 560bf6f1-70b3-446a-7dff-d13767852da6
  sha: sha256:1241381b2843fae5a9707eec1f8fb2ef94d827990582c7c7c32f5bdfbfd420c8
libffi/libffi-3.4.4.tar.gz:
  size: 1362394
  object_id: 893443d4-01f7-41d1-6990-178fecd10a3a
  sha: sha256:d66c56ad259a82cf2a9dfc408b32bf5da52371500b84745f7fb8b645712df676
python/Python-3.12.1.tgz:
  size: 27053241
  object_id: b760473d-9618-43a8-4fc7-44a7fc27f890
  sha: sha256:d01ec6a33bc10009b09c17da95cc2759af5a580a7316b3a446eb4190e13f97b2
sqlite/sqlite-autoconf-3450000.tar.gz:
  size: 3231697
  object_id: 8c0d1f56-06f5-4405-5b7a-8ae16f5fb320
  sha: sha256:72887d57a1d8f89f52be38ef84a6353ce8c3ed55ada7864eb944abd9a495e436
