---
platform: linux

image: docker:///cflondonservices/service-backups-release-ci

inputs:
- name: service-backup-release

run:
  path: service-backup-release/ci/scripts/cleanup_deployment.sh

params:
  BOSH_URL:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_DEPLOYMENT_NAMES:
