---
platform: linux

image: docker:///cflondonservices/service-backups-release-ci

inputs:
- name: service-backup-release

run:
  path: service-backup-release/ci/scripts/cleanup_deployment.sh

params:
  BOSH_URL:
  BOSH_CA_CERT_PATH:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT_NAMES:
