---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfservicesenablement/services-enablement-ci}

inputs:
- name: service-backup-release
- name: services-enablement-meta

run:
  path: service-backup-release/ci/scripts/cleanup_deployment.sh

params:
  BOSH_URL:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_DEPLOYMENT_NAMES:
